template_cpp: /home/marek/Documents/C++/lib/lib.o /home/marek/Documents/C++/lib/searching.o /home/marek/Documents/C++/lib/prints.o /home/marek/Documents/C++/lib/file_handling.o template_cpp.o
	g++ -o template_cpp /home/marek/Documents/C++/lib/lib.o /home/marek/Documents/C++/lib/searching.o /home/marek/Documents/C++/lib/prints.o /home/marek/Documents/C++/lib/file_handling.o template_cpp.o

template_cpp.o: template_cpp.cpp
	g++ -c template_cpp.cpp
	
clean:
	rm *.o template_cpp
